name: Create Mentioning Comment

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review:
    types: [submitted]

jobs:
  create:
    name: "Create"
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo gem install octokit yaml
      - name: Set Env Variables
        run: |
          echo "OUTSIDE_COLLABORATORS_GITHUB_REPO=${{ github.repository }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_EVENT_NAME=${{ github.event_name }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_ISSUE_NUMBER=${{ github.event.issue.number }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_PR_NUMBER=${{ github.event.pull_request.number }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_COMMENT_ID=${{ github.event.comment.id }}" >> ${GITHUB_ENV}
          echo "OUTSIDE_COLLABORATORS_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> ${GITHUB_ENV}
      - name: Run Handler
        run: |
          git clone https://github.com/${{ github.repository_owner }}/outside-collaborators.git --depth 1
          cd ./outside-collaborators/scripts
          ./mentioning-comment-handler.rb
